// Generated by MSXgl on 2025-09-20 21:40:20
#pragma once
#include "core.h"

// Language definition
#define LANG_EN 0
#define LANG_JA 1
#define LANG_NL 2
#define LANG_ES 3
#define LANG_PT 4
#define LANG_FR 5
#define LANG_UK 6
#define LANG_DE 7
#define LANG_IT 8
#define LANG_AR 9
#define LANG_DA 10
#define LANG_FI 11
#define LANG_SK 12
#define LANG_MAX 13

// Text ID definition
#define TEXT_TITLE 0
#define TEXT_MAX 1

// Localization data table
const c8* const g_LocData[LANG_MAX][TEXT_MAX] =
{
	// EN
	{
		"Happy new year 2024!", // TEXT_TITLE
	},
	// JA
	{
		"2024\x08 \x91\x99\xEF\x9C\xE3\x95\xF2\xE3\xDE\xE4\x93\x9A\xDE\x9B\xDE\x92\xEF\x9D!", // TEXT_TITLE
	},
	// NL
	{
		"Gelukkig nieuwjaar 2024!", // TEXT_TITLE
	},
	// ES
	{
		"\xAD\x46\x65liz a\xA4o nuevo 2024!", // TEXT_TITLE
	},
	// PT
	{
		"Feliz ano novo de 2024!", // TEXT_TITLE
	},
	// FR
	{
		"Bonne ann\x82\x65 2024!", // TEXT_TITLE
	},
	// UK
	{
		"\xFA \xEE\xCF\xD7\xC9\xCD 2024 \xD2\xCF\xCB\xCF\xCD!", // TEXT_TITLE
	},
	// DE
	{
		"Frohes neues Jahr 2024!", // TEXT_TITLE
	},
	// IT
	{
		"Buon anno 2024!", // TEXT_TITLE
	},
	// AR
	{
		"\x81\x32\x30\x32\x34\x80\xE4\xE5\xD4\xC0\xAF\x80\xE4\xE5\xD4\xE5\xA9\x80\xE4\xD0\xAF", // TEXT_TITLE
	},
	// DA
	{
		"Godt nyt\x86r 2024!", // TEXT_TITLE
	},
	// FI
	{
		"Hyv\x84\x84 uutta vuotta 2024!", // TEXT_TITLE
	},
	// SK
	{
		"Gott nytt \x86r 2024!", // TEXT_TITLE
	},
};